name: Java CI

on: [push]

jobs:
  build:
    name: Build and verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and run JUnit
      run: mvn -B clean install
    - name: Run JUnit and integration tests
      run: mvn -B verify
    - name: SonarCloud Scan
      run: mvn -B sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=kyvkri -Dsonar.projectKey=kyvkri_demo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}